version: "4.0"

services:

  front:
    build:
      context: front/netology-diplom-frontend
      dockerfile: Dockerfile
    container_name: cloud_front
    ports:
      - 8081:8080

  app:
    build:
          context: ./
          dockerfile: Dockerfile
    container_name: cloud_drive
    ports:
      - 8080:8080
    volumes:
      - /Users:/Users/
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/cloud_drive

  db:
    image: postgres
    container_name: cloud_db
    ports:
      - 5433:5432
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: alexey
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: cloud_drive

